### ISSUE TITLE
Multi-Threading Code Structure

### ISSUE THREAD

**Issue by bhimar** [uwigem/Chromastat18#3]
Investigate control flow of syringe pumps to identify which class to initialize threads in. (most likely PumpController Class)

**Comment by kwokwilliam** [comment]
If you want each individual pump to be on an individual thread, you would need the pump class to have the run() method. Currently, the PumpController class already extends Thread, which means the PumpController controls 3 pumps on a single thread.

**Comment by bhimar** [comment]
Right. I was thinking that the Pump Controller Class would still initialize the Pump Class (which would extend thread) thus creating the 3 threads. In which case the Pump Controller Class would just not extend thread. Do you think (to have the Pumps on individual threads), that I would scrap the Pump Controller Class and just contain everything in the Pump Class? @kwokwilliam
